In [171]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [172]:
dataset = pd.read_csv(r"E:\Practical Machine Learning\PML datasets\Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [190]:
# TAKING VALUES , because values can be converted into numpy array 
## if we 
x = dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values

In [174]:
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


<b>TaKing Care of Missing Data</b>

In [175]:
from sklearn.impute import SimpleImputer

In [176]:
imputer = SimpleImputer(missing_values=np.nan , strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] =  imputer.transform(x[:,1:3])

In [177]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


<b>Encoding Categorical Data

<b>Encoding the Independent Variable

In [178]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#to replace city column with 3 columns (dummy variables using sklearn)
#1transformers= [(action , the class object whowill do the transformation,
#colum index on which to appply transformation)]
#remainder = 'passthrough' will keep all other columns as it is, otherwise it will keep only
#newly created columns
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
#fit_transform does not return o/p in numpy arrray format it is array format
#and ML models will need the data in numpy array
x=np.array(ct.fit_transform(x))

In [179]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


<b> Encoding the Dependent Variable 

In [212]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y = le.fit_transform(y)

In [181]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [182]:
data ={ "age":[89,77,56,67,66,77],
      "gender":["female","male","male","male","female",np.NaN],
      "review":['good','good','bad','good','bad','good'],
      'education':['UG','PG','PHD','PG','UG','PHD'],
      'purchase':['yes','yes','no','yes','no','yes']}

In [183]:
df=pd.DataFrame(data)
df

age  gender review education purchase
0   89  female   good        UG      yes
1   77    male   good        PG      yes
2   56    male    bad       PHD       no
3   67    male   good        PG      yes
4   66  female    bad        UG       no
5   77     NaN   good       PHD      yes

In [184]:
from sklearn.impute import SimpleImputer 
#to replace age and salary column by corresponding mean value using sklearn

g=df.iloc[:,1].values
imputer =SimpleImputer(missing_values=np.NaN , strategy='most_frequent')
imputer.fit(g.reshape(-1,1))
g=imputer.transform(g.reshape(-1,1))
g
#df.iloc[:,1]=imputer.fit_transform(g)

array([['female'],
       ['male'],
       ['male'],
       ['male'],
       ['female'],
       ['male']], dtype=object)

In [195]:
df['gender']=g
df

city  age  gender review education purchase
0    spain   89  female   good        UG      yes
1  germany   77    male   good        PG      yes
2   france   56    male    bad       PHD       no
3    spain   67    male   good        PG      yes
4  germany   66  female    bad        UG       no
5   france   77    male   good       PHD      yes

In [186]:
city=['spain','germany','france','spain','germany','france']

In [187]:
df.insert(0, 'city', city )
df

city  age  gender review education purchase
0    spain   89  female   good        UG      yes
1  germany   77    male   good        PG      yes
2   france   56    male    bad       PHD       no
3    spain   67    male   good        PG      yes
4  germany   66  female    bad        UG       no
5   france   77     NaN   good       PHD      yes

In [188]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder =OneHotEncoder(drop = 'first', sparse=False)
x=df.iloc[:,0].values
x
one_hot_encoder.fit(x.reshape(-1,1))
x=one_hot_encoder.transform(x.reshape(-1,1))
x

C:\Users\KARTIK\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.]])

In [205]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['bad','good'],['UG','PG','PHD']])
data_ord=df.iloc[:,3:5]
#data_ord
model=oe.fit(data_ord)

In [206]:
model=oe.fit(data_ord)
model.categories_

[array(['bad', 'good'], dtype=object),
 array(['UG', 'PG', 'PHD'], dtype=object)]

In [216]:
model

OrdinalEncoder(categories=[['bad', 'good'], ['UG', 'PG', 'PHD']])

<b> Spliting the Dataset into the Training set and Test set

In [191]:
from sklearn.model_selection import train_test_split
#test_size =20% train_set=80%
#random_state=1
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
